# Generated by Django 3.2.25 on 2025-01-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_destination_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
