# Generated by Django 3.2.25 on 2025-01-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20250130_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default-profile.png', null=True, upload_to='profile_images/'),
        ),
    ]
