# Generated by Django 3.2.25 on 2025-01-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_country_moderator_place_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.CharField(default='No description available', max_length=255),
            preserve_default=False,
        ),
    ]
