# Generated by Django 3.2.25 on 2025-01-31 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20250131_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='travel.country'),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(default='Unknown location', max_length=255),
        ),
    ]
