# Generated by Django 3.2.25 on 2025-02-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_auto_20250131_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='thumbs_down_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='thumbs_up_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
