# Generated by Django 3.2.25 on 2025-02-02 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_auto_20250202_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='moderated_by',
        ),
        migrations.RemoveField(
            model_name='review',
            name='moderation_reason',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='moderated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
