# Generated by Django 3.2.25 on 2025-02-03 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_auto_20250202_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down')], max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='travel.review')),
            ],
            options={
                'unique_together': {('review', 'session_id')},
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
