# Generated by Django 5.1.7 on 2025-03-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_destination_alter_review_options_and_more'),
    ]

    operations = [
    ]
