# Generated by Django 5.1.7 on 2025-03-19 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_auto_20250319_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='destination',
        ),
        migrations.AddField(
            model_name='review',
            name='moderated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='place',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='travel.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='thumbs_down_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='thumbs_up_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
