# Generated by Django 3.2.25 on 2025-03-20 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_add_country_to_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='travel.destination'),
        ),
    ]
