# Generated by Django 3.2.25 on 2025-03-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_add_reviewimage_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/'),
        ),
    ]
