# Generated by Django 5.1.7 on 2025-03-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_auto_20250325_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='has_bias',
            field=models.BooleanField(default=False),
        ),
    ]
