# Generated by Django 5.1.7 on 2025-04-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_review_moderated_by_review_moderation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='moderated_by',
        ),
        migrations.RemoveField(
            model_name='review',
            name='moderation_date',
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
