# Generated by Django 3.2.25 on 2025-04-27 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0027_auto_20250411_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiasPreventionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_review_non_english', models.BooleanField(default=True, help_text='Require a second admin review for content in non-English languages.')),
                ('admin_decision_tracking', models.BooleanField(default=True, help_text='Enable tracking of individual moderator decisions for analytics.')),
                ('require_rejection_reason', models.BooleanField(default=True, help_text='Require moderators to provide a reason when rejecting a review.')),
                ('fairness_alert_threshold', models.IntegerField(default=15, help_text='Percentage difference in group approval rates to trigger a fairness alert (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='A unique code for the rejection reason (e.g., SPAM-01)', max_length=20, unique=True)),
                ('label', models.CharField(help_text='A short label for the rejection reason (e.g., Promotional Content)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='A detailed explanation of why content is rejected for this reason.')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
