# Generated by Django 3.2.25 on 2025-04-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0028_biaspreventionsettings_rejectionreason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BiasPreventionSettings',
        ),
        migrations.DeleteModel(
            name='RejectionReason',
        ),
    ]
