# Generated by Django 3.2.25 on 2025-04-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0029_auto_20250427_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_review_non_english', models.BooleanField(default=False)),
                ('admin_decision_tracking', models.BooleanField(default=True)),
                ('require_rejection_reason', models.BooleanField(default=True)),
                ('fairness_alert_threshold', models.CharField(choices=[('10', '10%'), ('15', '15%'), ('20', '20%')], default='15', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ReasonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
