# Generated by Django 3.2.25 on 2025-04-28 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0030_platformsetting_reasoncode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reasoncode',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='reasoncode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reasoncode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='admin_decision_tracking',
            field=models.BooleanField(default=True, help_text='Track moderator decisions for consistency analysis.'),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='fairness_alert_threshold',
            field=models.CharField(choices=[('10', '10%'), ('15', '15%'), ('20', '20%')], default='15', help_text='Threshold for triggering fairness alerts based on rejection rate differences.', max_length=3),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='require_rejection_reason',
            field=models.BooleanField(default=True, help_text='Mandate moderators to provide a reason when rejecting reviews.'),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='secondary_review_non_english',
            field=models.BooleanField(default=False, help_text='Enable secondary review for content detected as non-English.'),
        ),
        migrations.AlterField(
            model_name='reasoncode',
            name='code',
            field=models.CharField(help_text='Short, unique code (e.g., SPAM, HATE_SPEECH).', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reasoncode',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the reason code.'),
        ),
        migrations.AlterField(
            model_name='reasoncode',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this reason code is currently active and usable.'),
        ),
        migrations.AlterField(
            model_name='reasoncode',
            name='label',
            field=models.CharField(help_text='User-friendly label for the reason (e.g., Spam/Irrelevant Content).', max_length=100),
        ),
    ]
