# Generated by Django 3.2.25 on 2025-04-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0031_auto_20250428_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='platform_name',
            field=models.CharField(default='Travel Reviews', help_text='The public name of the platform.', max_length=100),
        ),
    ]
