# Generated by Django 3.2.25 on 2025-04-28 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0032_platformsetting_platform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='allow_anonymous_reviews',
            field=models.BooleanField(default=False, help_text='Allow users who are not logged in to submit reviews (requires careful moderation).'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='default_reviews_per_page',
            field=models.PositiveIntegerField(default=10, help_text='Default number of reviews shown per page (5-50).', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='enable_user_registration',
            field=models.BooleanField(default=True, help_text='Allow new users to register accounts.'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='minimum_review_length',
            field=models.PositiveIntegerField(default=50, help_text='Minimum number of characters required for review content.', validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='support_contact_email',
            field=models.EmailField(blank=True, help_text='Public contact email address for support inquiries (optional).', max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
