from django.urls import path
from . import views
from . import chatbot
from django.contrib.auth import views as auth_views
from .views import submit_review
from travel.views import assign_flagged_review 

urlpatterns = [
    path("", views.home, name="home"),  # Home page
    path("destinations/", views.destinations, name="destinations"),  # Destinations page
    path('destinations/greece/', views.greece, name='greece'),
    path('destinations/switzerland/', views.switzerland, name='switzerland'),
    path('destinations/New_Zealand/', views.New_Zealand, name='New_Zealand'),
    path('destinations/California/', views.California, name='California'),
    path('destinations/London/', views.London, name='London'),
    path('destinations/Tokyo/', views.Tokyo, name='Tokyo'),
    path('destinations/Rome/', views.Rome, name='Rome'),
    path('destinations/New_York/', views.New_York, name='New_York'),
    path('destinations/Sydney/', views.Sydney, name='Sydney'),
    path('destinations/Japan/', views.Japan, name='Japan'),
    path('destinations/Italy/', views.Italy, name='Italy'),
    path('destinations/Peru/', views.Peru, name='Peru'),
    path('destinations/China/', views.China, name='China'),
    path('destinations/Australia/', views.Australia, name='Australia'),
    path('destinations/Iceland/', views.Iceland, name='Iceland'),
    path('destinations/India/', views.India, name='India'),
    path('destinations/Egypt/', views.Egypt, name='Egypt'),
    path('destinations/Brazil/', views.Brazil, name='Brazil'),
    path('destinations/Paris/', views.Paris, name='Paris'),
    path('destinations/Morocco/', views.Morocco, name='Morocco'),
    path('destinations/Indonesia/', views.Indonesia, name='Indonesia'),
    path('destinations/Mumbai/', views.Mumbai, name='Mumbai'),
    path('destinations/Worlds_Beaches/', views.Worlds_Beach, name='Worlds_Beach'),
    path('destinations/Europe_Beach/', views.Europe_Beach, name='Europe_Beach'),
    path('destinations/Asia_Beach/', views.Asia_Beach, name='Asia_Beach'),
    path('destinations/South_Pacific_Beach/', views.South_Pacific_Beach, name='South_Pacific_Beach'),
    path('destinations/Caribbean_beach/', views.Caribbean_beach, name='Caribbean_beach'),
    path('destinations/Navagio_Beach/', views.Navagio_Beach, name='Navagio_Beach'),
    path('destinations/Maya_Bay/', views.Maya_Bay, name='Maya_Bay'),
    path('destinations/Seven_Mile_Beach/', views.Seven_Mile_Beach, name='Seven_Mile_Beach'),
    path('destinations/Matira_Beach/', views.Matira_Beach, name='Matira_Beach'),
    path('destinations/Sydney_Opera_House/', views.Sydney_Opera_House, name='Sydney_Opera_House'),
    path('destinations/Great_Barrier_Reef/', views.Great_Barrier_Reef, name='Great_Barrier_Reef'),
    path('destinations/Uluru/', views.Uluru, name='Uluru'),
    path('destinations/Twelve_Apostles/', views.Twelve_Apostles, name='Twelve_Apostles'),
    path('destinations/Rio_de_Janeiro/', views.Rio_de_Janeiro, name='Rio_de_Janeiro'),
    path('destinations/Amazon_Rainforest/', views.Amazon_Rainforest, name='Amazon_Rainforest'),
    path('destinations/Iguazu_Falls/', views.Iguazu_Falls, name='Iguazu_Falls'),
    path('destinations/Salvador/', views.Salvador, name='Salvador'),
    path('destinations/San_Francisco/', views.San_Francisco, name='San_Francisco'),
    path('destinations/Los_Angeles/', views.Los_Angeles, name='Los_Angeles'),
    path('destinations/Yosemite/', views.Yosemite, name='Yosemite'),
    path('destinations/Napa_Valley/', views.Napa_Valley, name='Napa_Valley'),
    path('submit-review/', views.submit_review, name='submit_review'),
    path('profile/', views.profile_view, name='profile'),
    path("about/", views.about, name="about"),  # About page
    path("contact/", views.contact, name="contact"),  # Contact page
    path("login/", views.login_view, name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="home"), name="logout"),
    path('register/', views.register_view, name='register'),
     path('profile/', views.profile_view, name='profile'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('upload-profile-image/', views.upload_profile_image, name='upload_profile_image'),
    path("api/places/", views.api_places, name="api_places"),
    path('review-action/', views.review_action, name='review_action'),
    path('moderator-dashboard/', views.moderator_dashboard, name='moderator_dashboard'),
    path('moderator-reviews/', views.moderator_reviews, name='moderator_reviews'),
    path('moderate-review/<int:review_id>/', views.moderator_reviews, name='moderate_review'),
    path('user/<int:user_id>/review-count/', views.user_review_count, name='user_review_count'),
    path("assign-flagged-review/", assign_flagged_review, name="assign-flagged-review"),
    path('search-results/', views.search, name='search_results'),
    path('search/', views.search, name='search'),
    path('explore/<str:country_name>/', views.explore_country, name='explore_country'),
    path('Backpacking/', views.Backpacking, name='Backpacking'),
    path('FoodAdventure/', views.FoodAdventure, name='FoodAdventure'),
    path('TravelBudget/', views.TravelBudget, name='TravelBudget'),
    path('PhotoGraphyGuide/', views.PhotoGraphyGuide, name='PhotoGraphyGuide'),
    path('SignUp/', views.SignUp, name='SignUp'),
    path('terms-of-service/', views.terms_page_view, name='terms_page'),
    path("logon/", views.Logon, name="logon"),
    path('upload-profile-image/', views.upload_profile_image, name='upload_profile_image'),
    path('api/user-reviews/', views.user_reviews, name='user_reviews'),
    path('edit-review/<int:review_id>/', views.edit_review, name='edit_review'),
    path('direct-update-review/<int:review_id>/', views.direct_update_review, name='direct_update_review'),
    path('user/delete-review/<int:review_id>/', views.user_delete_review, name='user_delete_review'),
    path('UserManagement/', views.User_management, name='User_management'),
    path('Appeal_review/', views.Appeal_review, name='Appeal_review'),
    path('analytics/', views.Analytics, name='Analytics'),
    path('api/analytics-stats/', views.analytics_stats_api, name='analytics_stats_api'),
    path('api/analytics-data/', views.analytics_data_api, name='analytics_data_api'),
    path('api/analytics-edit-stats/', views.analytics_edit_stats_api, name='analytics_edit_stats_api'),
    path('api/review-details/<int:review_id>/', views.get_review_details_api, name='get_review_details_api'),
    path('Settings/', views.Settings, name='Settings'),
    path('api/settings/get/', views.get_settings_data, name='get_settings_data'),
    path('api/settings/save/', views.save_settings_data, name='save_settings_data'),
    path('api/settings/reason-codes/list/', views.list_reason_codes, name='list_reason_codes'),
    path('api/settings/reason-codes/add/', views.add_reason_code, name='add_reason_code'),
    path('api/settings/reason-codes/update/<int:code_id>/', views.update_reason_code, name='update_reason_code'),
    path('api/settings/reason-codes/delete/<int:code_id>/', views.delete_reason_code, name='delete_reason_code'),
    path('reviews/<int:review_id>/', views.view_review, name='view_review'),
    path('reviews/<int:review_id>/edit/', views.edit_review, name='edit_review'),
    path('reviews/<int:review_id>/delete/', views.delete_review, name='delete_review'),
    path('api/user-demographics-data/', views.user_demographics_data, name='user_demographics_data'),
    path('api/user-activity-data/', views.user_activity_data, name='user_activity_data'),
    path('api/contribution-diversity-data/', views.contribution_diversity_data, name='contribution_diversity_data'),
    path('api/users/', views.users_api, name='users_api'),
    path('api/users/<int:user_id>/status/', views.user_status_api, name='user_status_api'),
    path('api/users/<int:user_id>/reset-password/', views.reset_password_api, name='reset_password_api'),
    path('delete-review/<int:review_id>/', views.delete_review, name='delete_review'),
    path('users/<int:user_id>/', views.user_profile_view, name='user_profile'),
    path('users/<int:user_id>/edit/', views.user_edit_view, name='user_edit'),
    path('api/review-trends/', views.review_trends_api, name='review_trends_api'),
    path('api/dashboard-trends/', views.dashboard_trends_api, name='dashboard_trends_api'),
    path('api/review-distribution/', views.review_distribution_api, name='review_distribution_api'),
    path('api/admin-performance-data/', views.get_admin_performance_data, name='admin_performance_data'),
    path('api/chat/', chatbot.chatbot_api, name='chat_api'),
    

    
    
    
    
    

    


]